server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active:  prod

  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

rollbar_token: c158e0e067304403b8cb5a4621ff83f7